language: php

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_script:
  - composer selfupdate
  - composer update --prefer-dist --no-interaction
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - benzari.alex@gmail.com
